# Generated by Django 5.2.15 on 2026-06-16 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateGraphic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graphic_type', models.CharField(max_length=50)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_filename', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=512)),
                ('file_size', models.BigIntegerField()),
                ('file_url', models.URLField(max_length=1024)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphics', to='affiliates.affiliate')),
            ],
        ),
    ]
